### ISSUE TITLE
feature: toasts on important success and failure events 

### ISSUE THREAD

**Issue by fastfists** [arguflow/vault-chat#17]
Create a UI component for error/success toasts that are styled via tailwind and triggered via the native EventListener API on the window object.

**Comment by anikdhabal** [comment]
@skeptrunedev Is this issue is not resolved yet? If not, then I am ready to work. This issue should be fix by using library like react-hot-toast or toastify. It will work like an API call and need to add test for the toaster.

**Comment by skeptrunedev** [comment]
> @skeptrunedev Is this issue not resolved yet? If not, then I am ready to work. This issue should be fix by using library like react-hot-toast or toastify. It will work like an API call and need to add test for the toaster.

This is a SolidJS repo and we would rather not use a library. Instead of a `context` based solution. We want to go with something that leverages the native EventTarget API - https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener . 

Rough example I was able to quickly inference w/ an LLM is below: 

```js
window.addEventListener('show-toast', (event) => {
  showToast(event.detail);
});

// Example: Trigger a toast notification using custom event on window
document.getElementById('show-toast-window-button').addEventListener('click', () => {
  const message = 'This is a toast from the window event';
  const toastEvent = new CustomEvent('show-toast', {
    detail: message,
  });
  window.dispatchEvent(toastEvent);
});
```

**Comment by algora-pbc** [comment]
💎 **$20** bounty created by @skeptrunedev
👉 To claim this bounty, [submit your pull request on Algora](https://console.algora.io/bounties/clmk1g6sx0006jr0ghb6xmf6i)
📝 Before proceeding, please make sure you can [**receive payouts**](https://docs.algora.io/bounties/payments#country-support) in your country
💵 Payment arrives in your account 2-5 days after the bounty is rewarded
💯 You keep 100% of the bounty award
🙏 Thank you for contributing to arguflow/vault-chat!

**Comment by anikdhabal** [comment]
@skeptrunedev can you assign me this issue?

**Comment by anikdhabal** [comment]
> > @skeptrunedev Is this issue not resolved yet? If not, then I am ready to work. This issue should be fix by using library like react-hot-toast or toastify. It will work like an API call and need to add test for the toaster.
> 
> This is a SolidJS repo and we would rather not use a library. Instead of a `context` based solution. We want to go with something that leverages the native EventTarget API - https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener .
> 
> Rough example I was able to quickly inference w/ an LLM is below:
> 
> ```js
> window.addEventListener('show-toast', (event) => {
>   showToast(event.detail);
> });
> 
> // Example: Trigger a toast notification using custom event on window
> document.getElementById('show-toast-window-button').addEventListener('click', () => {
>   const message = 'This is a toast from the window event';
>   const toastEvent = new CustomEvent('show-toast', {
>     detail: message,
>   });
>   window.dispatchEvent(toastEvent);
> });
> ```

Ahh understood, thank you.

**Comment by skeptrunedev** [comment]
/algora

> @skeptrunedev can you assign me this issue?

Assigned. To be clear, the deliverable here is to create UI components for error/success toasts that are styled via tailwind and triggered via the native EventListener API on the `window` object.

**Comment by anikdhabal** [comment]
> > @skeptrunedev can you assign me this issue?
> 
> Assigned. To be clear, the deliverable here is to create a UI component for error/success toasts that are styled via tailwind and triggered via the native EventListener API on the `window` object.

Yes, I will make a PR soon. Thank you🙏
